### ISSUE TITLE
no visual notification when there is an error

### ISSUE THREAD

**Issue by vampserv** [magnetsystems/message-samples-android#19]
If someone uses an invalid email, no visual notification is shown. error is thrown in logcat: 

02-02 14:05:53.794    2107-2107/com.magnet.magnetchat E/User﹕ user register error : {"errorCode":400,"errorMessage":"Username  cannot be null must be alphanumeric. Length should be (1- 255). Additional allowed Characters are (@#+-._-:)."}
02-02 14:05:53.798    2107-2107/com.magnet.magnetchat E/mMessage - register﹕ ERROR
    com.magnet.max.android.ApiError: {"errorCode":400,"errorMessage":"Username  cannot be null must be alphanumeric. Length should be (1- 255). Additional allowed Characters are (@#+-._-:)."}
            at com.magnet.max.android.ApiCallbackHelper.executeCallback(ApiCallbackHelper.java:37)
            at com.magnet.max.android.User$1.onFailure(User.java:86)
            at retrofit.MagnetCall$ExecutorCallback$2.run(MagnetCall.java:186)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: com.magnet.MagnetServiceException: {"errorCode":400,"errorMessage":"Username  cannot be null must be alphanumeric. Length should be (1- 255). Additional allowed Characters are (@#+-._-:)."}
            at retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:106)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by jimxj** [comment]
This seems related to #18.

@sanyadita , can you please fix this ?

**Comment by jimxj** [comment]
Fixed
