### ISSUE TITLE
unable to sign out

### ISSUE THREAD

**Issue by vampserv** [magnetsystems/message-samples-android#25]
when attempting to sign out using the navigation drawer Sign Out item, a toast is shown "Can't sign out" and logcat shows bad gateway error:

02-02 17:14:35.814    2234-2234/com.magnet.magnetchat D/MagnetRestAdapter﹕ MagnetRestAdapter : userToken invalidated  from thread 1
02-02 17:14:35.816    2234-2234/com.magnet.magnetchat E/mMessage - logout﹕ ERROR
    com.magnet.max.android.ApiError: <html>
    <head><title>502 Bad Gateway</title></head>
    <body bgcolor="white">
    <center><h1>502 Bad Gateway</h1></center>
    <hr><center>nginx/1.4.6 (Ubuntu)</center>
    </body>
    </html>
            at com.magnet.max.android.ApiCallbackHelper.executeCallback(ApiCallbackHelper.java:37)
            at com.magnet.max.android.User$4.onFailure(User.java:234)
            at retrofit.MagnetCall$ExecutorCallback$2.run(MagnetCall.java:186)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: com.magnet.MagnetServiceException: <html>
    <head><title>502 Bad Gateway</title></head>
    <body bgcolor="white">
    <center><h1>502 Bad Gateway</h1></center>
    <hr><center>nginx/1.4.6 (Ubuntu)</center>
    </body>
    </html>
            at retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:106)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by jimxj** [comment]
Fixed

**Comment by vampserv** [comment]
verified fixed
