### ISSUE TITLE
Change password does not work

### ISSUE THREAD

**Issue by vampserv** [magnetsystems/message-samples-android#27]
1. go tothe Change Password screen
2. fill in current password and new password fields
3. press submit.
4. app crashes with following error

02-03 17:13:11.075    4633-4633/com.magnet.magnetchat D/AndroidRuntime﹕ Shutting down VM
02-03 17:13:11.093    4633-4633/com.magnet.magnetchat E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.magnet.magnetchat, PID: 4633
    java.lang.NullPointerException: Attempt to read from null array
            at com.magnet.magnetchat.ui.ChangePasswordActivity.onClick(ChangePasswordActivity.java:34)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
02-03 17:13:11.795    4633-4663/com.magnet.magnetchat I/CrashlyticsCore﹕ C

**Comment by jimxj** [comment]
Hi Sandra, can you please fix this ?

**Comment by jimxj** [comment]
Fixed
